### ISSUE TITLE
How can I buy you a beer?

### ISSUE THREAD

**Issue by 1061147** [NMitchell24/CraftingCalculator#20]
Just found your app. its awesome, I owe you a beer, how can i donate?

**Comment by NMitchell24** [comment]
> Just found your app. its awesome, I owe you a beer, how can i donate?

Thank you.  I'm glad you enjoy the app.  One point of note, the data in it is a little out of date.  There are a few recipes missing and at least a couple that are wrong now due to updates in the game.  I need to fix those and plan on doing that soon, though I don't have an ETA right now on when the update will be available.  

As far as donations, I don't need that.  I do this for fun and the fact that you enjoy the app is all the donation I need.
